### ISSUE TITLE
Add node_modules to gitignore

### ISSUE THREAD

**Issue by joelnwalkley** [jdwilkin4/Black_Excellence_Project#2]
Hi there! Thanks so much for writing up your learning experience on freeCodeCamp, I learned a lot about the process and it is helpful to see that sometimes you just need to go for it make things a reality.

I have one recommendation so far: add a line to your gitignore for the node modules:
```
node_modules
```

Generally you don't commit those files to your repo. It tends to be huge which will use up all your free space on GitHub, commits and deploy will take longer, and the package.json will tell others how to fetch you dependencies from npm. There are additional steps to remove the node_modules from your git. [See this article, link.](https://dev.to/momentum/what-to-do-if-you-accidentally-committed-your-nodemodules-323o#:~:text=Tell%20git%20to%20ignore%20node_modules&text=Our%20first%20step%20is%20making,add%20more%20to%20it%20later.)

Also, I gotta say it was impressive to see you went for custom css for your styling! CSS is hard. Kudos to you.

**Comment by jdwilkin4** [comment]
Hi @joelnwalkley ! 

Thank you for your response! 

I have successfully added node modules to gitignore. 

Thanks again!
